export const NAVHEIGHT_VALUE = 'NAVHEIGHT_VALUE';

export const HTTP_ACTIONS = {
    LOADING: 'LOADING',
    SUCCESS: 'SUCCESS',
    ERROR: 'ERROR'
};

export const FETCH_MOVIES = {
    NEW_ON_NETFLIX: {
        LOADING: 'NEW_ON_NETFLIX_LOADING',
        SUCCESS: 'NEW_ON_NETFLIX_SUCCESS',
        ERROR: 'NEW_ON_NETFLIX_ERROR'
    },
    COMING_THIS_WEEK: {
        LOADING: 'COMING_THIS_WEEK_LOADING',
        SUCCESS: 'COMING_THIS_WEEK_SUCCESS',
        ERROR: 'COMING_THIS_WEEK_ERROR'
    },
    COMING_NEXT_WEEK: {
        LOADING: 'COMING_NEXT_WEEK_LOADING',
        SUCCESS: 'COMING_NEXT_WEEK_SUCCESS',
        ERROR: 'COMING_NEXT_WEEK_ERROR'
    },
    GET_MOVIE_BY_ID: {
        LOADING: 'GET_MOVIE_BY_ID_LOADING',
        SUCCESS: 'GET_MOVIE_BY_ID_SUCCESS',
        ERROR: 'GET_MOVIE_BY_ID_ERROR'
    }
};
